# Generated by Django 2.2 on 2021-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=400)),
                ('accountId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('accountType', models.CharField(max_length=6)),
                ('providerName', models.CharField(max_length=20)),
            ],
        ),
    ]
